import Foundation

enum LocalGalleryImports {
    static let boards: [LibraryBoard] = [
        LibraryBoard(
            id: "local-direction4-motion",
            promptTitle: "Motion Collage Study",
            itemCount: 4,
            updatedAtLabel: "Imported local",
            generationID: "gen-local-direction4-motion",
            items: [
                .init(
                    id: "local-direction4-motion-001",
                    kind: .image,
                    label: "Everything orbit motion",
                    previewColorHex: 0xBCBDBE,
                    secondaryColorHex: 0xC1C2C2,
                    generationID: "gen-local-direction4-motion",
                    bundleImageName: "image_recipe_app_everything_orbit_motion",
                    alt: "Animated collage of floating objects orbiting above a portrait",
                    source: nil,
                    author: "Direction 4"
                ),
                .init(
                    id: "local-direction4-motion-002",
                    kind: .image,
                    label: "Pop orbit",
                    previewColorHex: 0xFF7A1A,
                    secondaryColorHex: 0xA86DFF,
                    generationID: "gen-local-direction4-motion",
                    bundleImageName: "recipe-app-concept-2",
                    alt: "Playful campaign collage with objects orbiting around bold copy",
                    source: nil,
                    author: "Direction 4"
                ),
                .init(
                    id: "local-direction4-motion-003",
                    kind: .image,
                    label: "Tree scene",
                    previewColorHex: 0x7BBE4E,
                    secondaryColorHex: 0xB8D97D,
                    generationID: "gen-local-direction4-motion",
                    bundleImageName: "recipe-app-concept-3",
                    alt: "Stylized outdoor tableau with figures perched in a tree",
                    source: nil,
                    author: "Direction 4"
                ),
                .init(
                    id: "local-direction4-motion-004",
                    kind: .image,
                    label: "Air motion",
                    previewColorHex: 0x7198FF,
                    secondaryColorHex: 0xF49AE1,
                    generationID: "gen-local-direction4-motion",
                    bundleImageName: "recipe-app-concept-4",
                    alt: "Dynamic fashion figures suspended mid-air against a gradient sky",
                    source: nil,
                    author: "Direction 4"
                ),
            ]
        ),
        LibraryBoard(
            id: "local-direction5-exports",
            promptTitle: "Yellow Editorial Exports",
            itemCount: 9,
            updatedAtLabel: "Imported local",
            generationID: "gen-local-direction5-exports",
            items: [
                .init(
                    id: "local-direction5-exports-001",
                    kind: .image,
                    label: "Headmark portrait",
                    previewColorHex: 0xFCE83E,
                    secondaryColorHex: 0x992A25,
                    generationID: "gen-local-direction5-exports",
                    bundleImageName: "image_headmark_portrait",
                    alt: "Yellow editorial portrait with oversized NIKE wordmark and blue hair",
                    source: nil,
                    author: "Direction 5"
                ),
                .init(
                    id: "local-direction5-exports-002",
                    kind: .image,
                    label: "City tote crop",
                    previewColorHex: 0xEEDDB6,
                    secondaryColorHex: 0x785341,
                    generationID: "gen-local-direction5-exports",
                    bundleImageName: "image_city_tote_crop",
                    alt: "Low-angle fashion editorial with an oversized yellow tote in Times Square",
                    source: nil,
                    author: "Direction 5"
                ),
                .init(
                    id: "local-direction5-exports-005",
                    kind: .image,
                    label: "Get Into It poster",
                    previewColorHex: 0xFFFE91,
                    secondaryColorHex: 0x7CA584,
                    generationID: "gen-local-direction5-exports",
                    bundleImageName: "image_get_into_it_poster",
                    alt: "Poster-style yellow editorial with GET INTO IT typography and activewear styling",
                    source: nil,
                    author: "Direction 5"
                ),
                .init(
                    id: "local-direction5-exports-004",
                    kind: .image,
                    label: "Bold wordmark",
                    previewColorHex: 0xFED000,
                    secondaryColorHex: 0x362F08,
                    generationID: "gen-local-direction5-exports",
                    bundleImageName: "image_bold_wordmark",
                    alt: "Black condensed wordmark on a bright yellow field",
                    source: nil,
                    author: "Direction 5"
                ),
                .init(
                    id: "local-direction5-exports-003",
                    kind: .image,
                    label: "Lime motion crop",
                    previewColorHex: 0x717A6D,
                    secondaryColorHex: 0x96914C,
                    generationID: "gen-local-direction5-exports",
                    bundleImageName: "image_lime_motion_crop",
                    alt: "Low-angle crop of a neon yellow garment moving against a pale sky",
                    source: nil,
                    author: "Direction 5"
                ),
                .init(
                    id: "local-direction5-exports-006",
                    kind: .image,
                    label: "Lime motion square",
                    previewColorHex: 0x71796C,
                    secondaryColorHex: 0x938F4F,
                    generationID: "gen-local-direction5-exports",
                    bundleImageName: "image_lime_motion_square",
                    alt: "Square crop of neon yellow fashion motion against open sky",
                    source: nil,
                    author: "Direction 5"
                ),
                .init(
                    id: "local-direction5-exports-007",
                    kind: .image,
                    label: "Wordmark square",
                    previewColorHex: 0xFED000,
                    secondaryColorHex: 0x3F3608,
                    generationID: "gen-local-direction5-exports",
                    bundleImageName: "image_wordmark_square",
                    alt: "Square yellow wordmark lockup in bold black typography",
                    source: nil,
                    author: "Direction 5"
                ),
                .init(
                    id: "local-direction5-exports-009",
                    kind: .image,
                    label: "Get Into It cover",
                    previewColorHex: 0xFFFF91,
                    secondaryColorHex: 0x7CA584,
                    generationID: "gen-local-direction5-exports",
                    bundleImageName: "image_get_into_it_cover",
                    alt: "Square cover crop of the GET INTO IT campaign poster in yellow activewear",
                    source: nil,
                    author: "Direction 5"
                ),
                .init(
                    id: "local-direction5-exports-010",
                    kind: .image,
                    label: "City tote frame",
                    previewColorHex: 0xEDDDB6,
                    secondaryColorHex: 0x775341,
                    generationID: "gen-local-direction5-exports",
                    bundleImageName: "image_city_tote_frame",
                    alt: "Framed crop of a yellow tote editorial shot in Times Square",
                    source: nil,
                    author: "Direction 5"
                ),
            ]
        ),
        LibraryBoard(
            id: "local-home-09",
            promptTitle: "09 Screen Captures",
            itemCount: 7,
            updatedAtLabel: "Imported local",
            generationID: "gen-local-home-09",
            items: [
                .init(
                    id: "local-home-09-001",
                    kind: .image,
                    label: "Cream mist",
                    previewColorHex: 0xFFFFFF,
                    secondaryColorHex: 0xFFFFFF,
                    generationID: "gen-local-home-09",
                    bundleImageName: "color_cream_mist",
                    alt: "Very light cream screen capture swatch",
                    source: nil,
                    author: "home / 09_files"
                ),
                .init(
                    id: "local-home-09-002",
                    kind: .image,
                    label: "Pale butter",
                    previewColorHex: 0xFFF792,
                    secondaryColorHex: 0xFFF793,
                    generationID: "gen-local-home-09",
                    bundleImageName: "color_pale_butter",
                    alt: "Pale butter yellow screen capture swatch",
                    source: nil,
                    author: "home / 09_files"
                ),
                .init(
                    id: "local-home-09-003",
                    kind: .image,
                    label: "Yellow glow",
                    previewColorHex: 0xFFF6B0,
                    secondaryColorHex: 0xFFFEF4,
                    generationID: "gen-local-home-09",
                    bundleImageName: "color_yellow_glow",
                    alt: "Soft yellow glow screen capture swatch",
                    source: nil,
                    author: "home / 09_files"
                ),
                .init(
                    id: "local-home-09-007",
                    kind: .image,
                    label: "Soft vanilla",
                    previewColorHex: 0xFFFCB7,
                    secondaryColorHex: 0xFFFCB7,
                    generationID: "gen-local-home-09",
                    bundleImageName: "color_soft_vanilla",
                    alt: "Soft vanilla cream screen capture swatch",
                    source: nil,
                    author: "home / 09_files"
                ),
                .init(
                    id: "local-home-09-008",
                    kind: .image,
                    label: "Apricot wash",
                    previewColorHex: 0xFEDB67,
                    secondaryColorHex: 0xFEDB67,
                    generationID: "gen-local-home-09",
                    bundleImageName: "color_apricot_wash",
                    alt: "Apricot yellow screen capture swatch",
                    source: nil,
                    author: "home / 09_files"
                ),
                .init(
                    id: "local-home-09-006",
                    kind: .image,
                    label: "Electric yellow",
                    previewColorHex: 0xFFF001,
                    secondaryColorHex: 0xFFF001,
                    generationID: "gen-local-home-09",
                    bundleImageName: "color_electric_yellow",
                    alt: "Electric yellow screen capture swatch",
                    source: nil,
                    author: "home / 09_files"
                ),
                .init(
                    id: "local-home-09-005",
                    kind: .image,
                    label: "Aqua wash",
                    previewColorHex: 0xBCF3F0,
                    secondaryColorHex: 0xBCF3F0,
                    generationID: "gen-local-home-09",
                    bundleImageName: "color_aqua_wash",
                    alt: "Light aqua screen capture swatch",
                    source: nil,
                    author: "home / 09_files"
                ),
            ]
        ),
        LibraryBoard(
            id: "local-home-color",
            promptTitle: "Home Color Swatches",
            itemCount: 14,
            updatedAtLabel: "Imported local",
            generationID: "gen-local-home-color",
            items: [
                .init(
                    id: "local-home-color-001",
                    kind: .image,
                    label: "Punch red",
                    previewColorHex: 0xE23634,
                    secondaryColorHex: 0xE43534,
                    generationID: "gen-local-home-color",
                    bundleImageName: "color_punch_red",
                    alt: "Flat red color swatch",
                    source: nil,
                    author: "home / color"
                ),
                .init(
                    id: "local-home-color-002",
                    kind: .image,
                    label: "Hot pink haze",
                    previewColorHex: 0xFF85CE,
                    secondaryColorHex: 0xFF8BD5,
                    generationID: "gen-local-home-color",
                    bundleImageName: "color_hot_pink_haze",
                    alt: "Soft hot pink color swatch",
                    source: nil,
                    author: "home / color"
                ),
                .init(
                    id: "local-home-color-003",
                    kind: .image,
                    label: "Rose pink",
                    previewColorHex: 0xEE77A1,
                    secondaryColorHex: 0xEE77A1,
                    generationID: "gen-local-home-color",
                    bundleImageName: "color_rose_pink",
                    alt: "Rose pink color swatch",
                    source: nil,
                    author: "home / color"
                ),
                .init(
                    id: "local-home-color-004",
                    kind: .image,
                    label: "Melon orange",
                    previewColorHex: 0xEF9F58,
                    secondaryColorHex: 0xF09F58,
                    generationID: "gen-local-home-color",
                    bundleImageName: "color_melon_orange",
                    alt: "Warm melon orange color swatch",
                    source: nil,
                    author: "home / color"
                ),
                .init(
                    id: "local-home-color-005",
                    kind: .image,
                    label: "Ultramarine blur",
                    previewColorHex: 0x1F03EB,
                    secondaryColorHex: 0x2003EB,
                    generationID: "gen-local-home-color",
                    bundleImageName: "color_ultramarine_blur",
                    alt: "Ultramarine blue swatch with soft ripple texture",
                    source: nil,
                    author: "home / color"
                ),
                .init(
                    id: "local-home-color-006",
                    kind: .image,
                    label: "Citrus lime",
                    previewColorHex: 0xB2EB84,
                    secondaryColorHex: 0xB1EA83,
                    generationID: "gen-local-home-color",
                    bundleImageName: "color_citrus_lime",
                    alt: "Bright citrus lime color swatch",
                    source: nil,
                    author: "home / color"
                ),
                .init(
                    id: "local-home-color-007",
                    kind: .image,
                    label: "Powder blush",
                    previewColorHex: 0xFACBDF,
                    secondaryColorHex: 0xFACBDF,
                    generationID: "gen-local-home-color",
                    bundleImageName: "color_powder_blush",
                    alt: "Powder blush pink swatch",
                    source: nil,
                    author: "home / color"
                ),
                .init(
                    id: "local-home-color-008",
                    kind: .image,
                    label: "Butter cream",
                    previewColorHex: 0xFFDF96,
                    secondaryColorHex: 0xFEE099,
                    generationID: "gen-local-home-color",
                    bundleImageName: "color_butter_cream",
                    alt: "Soft butter cream swatch",
                    source: nil,
                    author: "home / color"
                ),
                .init(
                    id: "local-home-color-009",
                    kind: .image,
                    label: "Teal pool",
                    previewColorHex: 0x158088,
                    secondaryColorHex: 0x158088,
                    generationID: "gen-local-home-color",
                    bundleImageName: "color_teal_pool",
                    alt: "Teal pool color swatch",
                    source: nil,
                    author: "home / color"
                ),
                .init(
                    id: "local-home-color-010",
                    kind: .image,
                    label: "Magenta beam",
                    previewColorHex: 0xB01DFF,
                    secondaryColorHex: 0xAE1BFF,
                    generationID: "gen-local-home-color",
                    bundleImageName: "color_magenta_beam",
                    alt: "Magenta gradient beam swatch",
                    source: nil,
                    author: "home / color"
                ),
                .init(
                    id: "local-home-color-011",
                    kind: .image,
                    label: "Lavender mist",
                    previewColorHex: 0xAB96D1,
                    secondaryColorHex: 0xAB96D1,
                    generationID: "gen-local-home-color",
                    bundleImageName: "color_lavender_mist",
                    alt: "Lavender mist color swatch",
                    source: nil,
                    author: "home / color"
                ),
                .init(
                    id: "local-home-color-012",
                    kind: .image,
                    label: "Cobalt pop",
                    previewColorHex: 0x0260FD,
                    secondaryColorHex: 0x0261FD,
                    generationID: "gen-local-home-color",
                    bundleImageName: "color_cobalt_pop",
                    alt: "Bright cobalt blue swatch",
                    source: nil,
                    author: "home / color"
                ),
                .init(
                    id: "local-home-color-013",
                    kind: .image,
                    label: "Fuchsia pop",
                    previewColorHex: 0xFD0072,
                    secondaryColorHex: 0xFD0171,
                    generationID: "gen-local-home-color",
                    bundleImageName: "color_fuchsia_pop",
                    alt: "Bright fuchsia pink swatch",
                    source: nil,
                    author: "home / color"
                ),
                .init(
                    id: "local-home-color-014",
                    kind: .image,
                    label: "Mulberry bloom",
                    previewColorHex: 0xBC3A68,
                    secondaryColorHex: 0xBC3A68,
                    generationID: "gen-local-home-color",
                    bundleImageName: "color_mulberry_bloom",
                    alt: "Mulberry rose color swatch",
                    source: nil,
                    author: "home / color"
                ),
            ]
        ),
        LibraryBoard(
            id: "local-home-imagery-pinterest",
            promptTitle: "Pinterest Garden Studies I",
            itemCount: 11,
            updatedAtLabel: "Imported local",
            generationID: "gen-local-home-imagery-pinterest",
            items: [
                .init(
                    id: "local-home-imagery-pinterest-006",
                    kind: .image,
                    label: "Wildflower meadow",
                    previewColorHex: 0x777332,
                    secondaryColorHex: 0x203014,
                    generationID: "gen-local-home-imagery-pinterest",
                    bundleImageName: "image_pinterest_wildflower_meadow",
                    alt: "Painterly field of orange and cream wildflowers",
                    source: nil,
                    author: "home / imagery / Pinterest_files"
                ),
                .init(
                    id: "local-home-imagery-pinterest-008",
                    kind: .image,
                    label: "Butterfly meadow",
                    previewColorHex: 0xA7A474,
                    secondaryColorHex: 0x8F9161,
                    generationID: "gen-local-home-imagery-pinterest",
                    bundleImageName: "image_pinterest_butterfly_meadow",
                    alt: "Blurry floral meadow with a butterfly drifting through frame",
                    source: nil,
                    author: "home / imagery / Pinterest_files"
                ),
                .init(
                    id: "local-home-imagery-pinterest-011",
                    kind: .image,
                    label: "Willow light",
                    previewColorHex: 0x9A8E7B,
                    secondaryColorHex: 0xE6DAC5,
                    generationID: "gen-local-home-imagery-pinterest",
                    bundleImageName: "image_pinterest_willow_light",
                    alt: "Hazy willow grove reflecting soft light over water",
                    source: nil,
                    author: "home / imagery / Pinterest_files"
                ),
                .init(
                    id: "local-home-imagery-pinterest-004",
                    kind: .image,
                    label: "Lily pond blur",
                    previewColorHex: 0xA09064,
                    secondaryColorHex: 0xA7A986,
                    generationID: "gen-local-home-imagery-pinterest",
                    bundleImageName: "image_pinterest_lily_pond_blur",
                    alt: "Soft blurred impression of a lily pond with warm highlights",
                    source: nil,
                    author: "home / imagery / Pinterest_files"
                ),
                .init(
                    id: "local-home-imagery-pinterest-001",
                    kind: .image,
                    label: "Rolling wildflower hills",
                    previewColorHex: 0x121F14,
                    secondaryColorHex: 0xA6C5BC,
                    generationID: "gen-local-home-imagery-pinterest",
                    bundleImageName: "image_pinterest_rolling_wildflower_hills",
                    alt: "Painterly hills with bands of flowers under a blue sky",
                    source: nil,
                    author: "home / imagery / Pinterest_files"
                ),
                .init(
                    id: "local-home-imagery-pinterest-002",
                    kind: .image,
                    label: "Soft blank field",
                    previewColorHex: 0xFFFFFF,
                    secondaryColorHex: 0xFFFFFF,
                    generationID: "gen-local-home-imagery-pinterest",
                    bundleImageName: "image_pinterest_soft_blank_field",
                    alt: "Near-white minimal field with a soft cream tint",
                    source: nil,
                    author: "home / imagery / Pinterest_files"
                ),
                .init(
                    id: "local-home-imagery-pinterest-010",
                    kind: .image,
                    label: "Bouquet motion",
                    previewColorHex: 0x926F5A,
                    secondaryColorHex: 0xBA9480,
                    generationID: "gen-local-home-imagery-pinterest",
                    bundleImageName: "image_pinterest_bouquet_motion",
                    alt: "Floral bouquet motion blur around two figures in patterned clothing",
                    source: nil,
                    author: "home / imagery / Pinterest_files"
                ),
                .init(
                    id: "local-home-imagery-pinterest-009",
                    kind: .image,
                    label: "Dusk lakeside",
                    previewColorHex: 0xB0969A,
                    secondaryColorHex: 0x665B6A,
                    generationID: "gen-local-home-imagery-pinterest",
                    bundleImageName: "image_pinterest_dusk_lakeside",
                    alt: "Dusky lakeside landscape framed by branches in soft pink light",
                    source: nil,
                    author: "home / imagery / Pinterest_files"
                ),
                .init(
                    id: "local-home-imagery-pinterest-005",
                    kind: .image,
                    label: "Forest contact grid",
                    previewColorHex: 0x464F3F,
                    secondaryColorHex: 0x293123,
                    generationID: "gen-local-home-imagery-pinterest",
                    bundleImageName: "image_pinterest_forest_contact_grid",
                    alt: "Grid collage of moody forest and waterfall scenes",
                    source: nil,
                    author: "home / imagery / Pinterest_files"
                ),
                .init(
                    id: "local-home-imagery-pinterest-007",
                    kind: .image,
                    label: "Desert dune study",
                    previewColorHex: 0x4D3A1D,
                    secondaryColorHex: 0x385D8D,
                    generationID: "gen-local-home-imagery-pinterest",
                    bundleImageName: "image_pinterest_desert_dune_study",
                    alt: "Minimal study of shadowed desert dunes under a cobalt sky",
                    source: nil,
                    author: "home / imagery / Pinterest_files"
                ),
                .init(
                    id: "local-home-imagery-pinterest-003",
                    kind: .image,
                    label: "Night meadow runner",
                    previewColorHex: 0x021323,
                    secondaryColorHex: 0x957444,
                    generationID: "gen-local-home-imagery-pinterest",
                    bundleImageName: "image_pinterest_night_meadow_runner",
                    alt: "Figure running through a meadow at night with dramatic light",
                    source: nil,
                    author: "home / imagery / Pinterest_files"
                ),
            ]
        ),
    ]
}
